# Generated by Django 3.2 on 2023-01-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='ref',
            field=models.CharField(blank=True, max_length=23),
        ),
    ]
