# Generated by Django 3.2 on 2023-01-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywallet', '0003_auto_20230129_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain',
            name='id_chain',
            field=models.CharField(max_length=42),
        ),
    ]
