# Generated by Django 3.2 on 2023-01-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywallet', '0004_alter_blockchain_id_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='id_blockchain',
            field=models.CharField(max_length=42),
        ),
    ]
