# Generated by Django 3.2 on 2023-01-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywallet', '0005_alter_token_id_blockchain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='fiat_amount',
        ),
        migrations.RemoveField(
            model_name='token',
            name='fiat_amount_currency',
        ),
        migrations.RemoveField(
            model_name='token',
            name='is_active',
        ),
        migrations.AddField(
            model_name='usertoken',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
