# Generated by Django 3.2 on 2023-01-29 15:45

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mywallet', '0006_auto_20230129_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='fiat_value',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=14),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='owner_ref',
            field=models.CharField(max_length=36),
        ),
    ]
