# Generated by Django 3.2 on 2023-02-02 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywallet', '0007_auto_20230129_1645'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserToken',
            new_name='EntityToken',
        ),
    ]
