# Generated by Django 3.2 on 2023-02-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywallet', '0008_rename_usertoken_entitytoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='ref',
            field=models.CharField(blank=True, max_length=23, unique=True),
        ),
    ]
