# Generated by Django 3.2 on 2023-02-02 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx_ref', models.CharField(max_length=44)),
                ('ops_type', models.CharField(choices=[('TOPUP', 'Top up'), ('WIRE_TRANSFER', 'Wire Transfer'), ('P2P_TRANSFER', 'Peer To Peer Transfer'), ('WITHDRAW', 'Withdraw')], max_length=14)),
                ('from_wallet', models.CharField(max_length=23)),
                ('to_wallet', models.CharField(max_length=23)),
                ('id_blockchain', models.CharField(max_length=42)),
                ('token_code', models.CharField(max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
