# Generated by Django 3.2 on 2023-02-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_rename_tokenoperation_walletoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletoperation',
            name='to_external_wallet',
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AlterField(
            model_name='walletoperation',
            name='ops_type',
            field=models.CharField(choices=[('TOP_UP', 'Top up'), ('FIAT_TOP_UP', 'Fiat Top up'), ('WIRE_TRANSFER', 'Wire Transfer'), ('FIAT_WIRE_TRANSFER', 'Fiat Wire Transfer'), ('WITHDRAW', 'Withdraw'), ('FIAT_WITHDRAW', 'Fiat Withdraw')], max_length=18),
        ),
    ]
