# Generated by Django 3.2 on 2023-02-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_expiry_date',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='operator',
            field=models.CharField(choices=[('BANK', 'Bank'), ('MOMO', 'Mobile money')], max_length=25),
        ),
    ]
