# Generated by Django 3.2 on 2023-02-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_auto_20230216_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(choices=[('MTNMOMO', 'MTN Mobile money'), ('OM', 'Orange Money'), ('MASTERCARD', 'Mastercard'), ('VISA', 'Visa Card'), ('PAYPAL', 'Paypal')], max_length=25),
        ),
    ]
